version: '2'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"   # Map container's NameNode web UI (9870) to host's port 9870
      - "9000:9000"   # HDFS NameNode service port
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9864:9864"   # DataNode web UI port
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_USER=root
      - HIVE_METASTORE_PASSWORD=root
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "9083:9083"
    depends_on:
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore

volumes:
  namenode:
  datanode:
